required = ["github.com/sepuka/gonerator/number"]
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "1.2.1"
[[constraint]]
  name = "github.com/google/uuid"
  version = "1.3.0"